version: "3.7"

services: 
    sentilis-tona:
        container_name: sentilis-tona
        build: .
        ports: 
            - 5001:5001
        #volumes: # Persist data storage
        #    - ./storage:/tona/storage
        #environment:
        #    TONA_TZ: America/Mexico_City